Update release notes instructions in Contributing docs
fedora-infra/fedora-messaging pull request #238
Opened 2021-06-11 00:27 UTC by dvejmz

Make release notes instructions slightly more specific, which may be useful for first time contributors. News fragment update will follow soon.

2021-06-11 06:53 UTC, abompard requested changes
Thanks! I hadn't noticed that towncrier now has subcommands.

2021-06-11 06:53 UTC, abompard commented on news/PR238.other
> +Improve release notes process documentation.
I would suggest the type `docs` instead of `other` here.

2021-06-11 06:53 UTC, abompard commented on docs/contributing.rst
> +To add entries to the release notes, run ``towncrier create <source.type>`` to create a news fragment file in the ``news`` directory, where ``type`` is one of:
Could you wrap this line like the others please?

2021-06-11 06:53 UTC, abompard commented on docs/contributing.rst
> +The contents of the news fragment must be written in RST format. See the `towncrier documentation for more information <https://github.com/twisted/towncrier>`_.
Same here

2021-06-11 21:25 UTC, dvejmz commented
Thanks for your comments @abompard , I've now addressed them all.

2021-09-29 12:03 UTC, abompard requested changes
I'm only getting around to looking at this now, sorry. Just a small typo. Thanks!

2021-09-29 12:03 UTC, abompard commented on docs/contributing.rst
> +See the `towncrier documentation formore information
Missing space here

2021-10-03 20:38 UTC, dvejmz commented
No problem, I've now pushed a fix @abompard

2021-10-04 09:14 UTC, abompard approved these changes

2021-10-04 09:14 UTC, merged