Use Reuse for the license
fedora-infra/fedora-messaging pull request #422
Opened 2024-12-12 14:34 UTC by olamidepeterojo

Fixes #383

2024-12-17 09:59 UTC, abompard requested changes

2024-12-17 09:59 UTC, abompard commented on fedora_messaging/__init__.py
> +/*
This is C/Javascript-style comments. In Python comments start with a `#`.

2024-12-17 09:59 UTC, abompard commented on fedora_messaging/__init__.py
> + * SPDX-License-Identifier: GPL-3.0-or-later
The license is actually `GPL-2.0-or-later`.

2024-12-17 11:27 UTC, olamidepeterojo commented on fedora_messaging/__init__.py
> + * SPDX-License-Identifier: GPL-3.0-or-later
okay, although someone asked what version of GPL you preferred and you said GPL-3.0-or-later, that's why i made use of it

2024-12-17 11:30 UTC, olamidepeterojo commented on fedora_messaging/__init__.py
> +/*
My apologies, i will amend it.

2024-12-18 08:44 UTC, abompard commented on fedora_messaging/__init__.py
> + * SPDX-License-Identifier: GPL-3.0-or-later
Let's not change the license from what it was before, even though I would prefer GPL-3.0-or-later, the code is currently under GPL-2.0-or-later.

2024-12-18 09:54 UTC, olamidepeterojo commented on fedora_messaging/__init__.py
> + * SPDX-License-Identifier: GPL-3.0-or-later
Alright, I'll update it to GPL-2.0-or-later.

2024-12-19 13:39 UTC, abompard requested changes
This PR is lacking the Reuse check itself. You can for example use this block in `.pre-commit-config.yml` :

```
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
```

2024-12-19 13:39 UTC, abompard commented on docs/sample_schema_package/mailman_messages/__init__.py
> +# the Free Software Foundation; either version 3 of the License, or
This is still changing the license. By the way, if you start using the `SPDX-License-Identifier` tag, you can drop this block of text.

2025-01-02 15:21 UTC, abompard requested changes
Some more comments, mostly related to using a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file.

2025-01-02 15:21 UTC, abompard commented on tox.ini
> +; SPDX-FileCopyrightText: 2024 Red Hat, Inc
Those two lines seem redundant.

2025-01-02 15:21 UTC, abompard commented on tests/integration/test_cli.py
>  # Copyright (C) 2019 Red Hat, Inc.
You can drop this line as well.

2025-01-02 15:21 UTC, abompard commented on tests/fixtures/wrong_json_msg_dump.txt
> +SPDX-License-Identifier: GPL-2.0-or-later
This does not make sense for a test fixture, I would add the fixtures to a block in a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file, using a wildcard, such as:

```toml
# Test fixtures
[[annotations]]
path = ["tests/fixtures/*"]
SPDX-FileCopyrightText = "2024 Red Hat, Inc"
SPDX-License-Identifier = "GPL-2.0-or-later"
```

This applies to all the files in this directory.

2025-01-02 15:21 UTC, abompard commented on pyproject.toml
> +license = "GPLv3+"
Please don't change the license.

2025-01-02 15:21 UTC, abompard commented on pyproject.toml
> +# SPDX-License-Identifier: GPL-2.0-or-later
It does not make much sense in the case of this file, because we're talking about project configuration here.
I would add these files to a block in a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file, such as:

```toml
# Project configuration
[[annotations]]
path = ["pyproject.toml", "poetry.lock", "codecov.yml", ".*.yml", ".*.yaml", "CODEOWNERS"]
SPDX-FileCopyrightText = "2024 Red Hat, Inc"
SPDX-License-Identifier = "GPL-2.0-or-later"
```

2025-01-02 15:21 UTC, abompard commented on packit/installation/main.fmf
> +
Let's just cover that with a REUSE.toml block like others.

2025-01-02 15:21 UTC, abompard commented on news/383.docs.md
> +<!--
It does not make much sense for news fragments, because they are documentation files that will be aggregated into the release notes and removed.
I would add these files to a block in a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file, such as:

```toml
# News fragments
[[annotations]]
path = ["news/*"]
SPDX-FileCopyrightText = "2024 Red Hat, Inc"
SPDX-License-Identifier = "GPL-2.0-or-later"
```

2025-01-02 15:21 UTC, abompard commented on fedora_messaging/twisted/consumer.py
>  # Copyright (C) 2019 Red Hat, Inc.
This can be dropped as well.

2025-01-02 15:21 UTC, abompard commented on docs/schema-packages.txt
> +SPDX-License-Identifier: GPL-2.0-or-later
Please add the hash sign at the beginning of those lines to mark them as comments.

2025-01-02 15:21 UTC, abompard commented on devel/run-liccheck.sh
> -#!/bin/bash
Please leave this line in place.

2025-01-02 15:21 UTC, abompard commented on configs/cacert.pem.license
> +SPDX-FileCopyrightText: 2024 Red Hat, Inc
All the files in `configs` can also be covered by a block in a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file, such as:

```toml
# configs
[[annotations]]
path = ["configs/*"]
SPDX-FileCopyrightText = "2024 Red Hat, Inc"
SPDX-License-Identifier = "GPL-2.0-or-later"
```

2025-01-02 15:21 UTC, abompard commented on .fmf/version
> +SPDX-FileCopyrightText: 2024 Red Hat, Inc
The FMF config files can be covered by a block in a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file, such as:

```toml
# FMF
[[annotations]]
path = [".fmf/version", "packit/installation/*.fmf"]
SPDX-FileCopyrightText = "2024 Red Hat, Inc"
SPDX-License-Identifier = "GPL-2.0-or-later"
```

2025-01-07 22:52 UTC, olamidepeterojo commented
hello, i've made the changes as requested but when i run `reuse lint` it fails saying the following files listed below do not have license

* configs\cacert.pem
* configs\fedora-cert.pem
* configs\fedora-key.pem
* configs\fedora.stg-cert.pem
* configs\fedora.stg-key.pem
* configs\stg-cacert.pem
* tests\fixtures\ca_bundle.pem
* tests\fixtures\cert.pem
* tests\fixtures\key.pem

2025-01-08 13:02 UTC, abompard commented
Yes, you can use a [REUSE.toml](https://reuse.software/spec-3.3/#reusetoml) file to cover those files, as indicated in the comments. I don't see it, maybe you forgot to add it to the repo with `git add`?

2025-01-08 19:20 UTC, olamidepeterojo commented
I'm surprised as well. i thought i did cause usually i `git add .`

2025-02-14 15:32 UTC, abompard requested changes
Some duplication between inline changes and `REUSE.toml`, and a couple comments about usage of wildcards.

2025-02-14 15:32 UTC, abompard commented on REUSE.toml
> +path = ["tests/fixtures/key.pem"]
You could actually use a wildcard here: `tests/fixtures/*`. This will make the file much more readable.

2025-02-14 15:32 UTC, abompard commented on CODEOWNERS
> +
You no longer need this since you have flagged this file in `REUSE.toml`.

2025-02-14 15:32 UTC, abompard commented on LICENSE
> - Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
You can actually delete this file, it's replaced by the one in the `LICENSES` directory.

2025-02-14 15:32 UTC, abompard commented on poetry.lock.license
> +SPDX-FileCopyrightText: 2024 Red Hat, Inc
You don't need this file since you flagged `poetry.lock` in `REUSE.toml`.

2025-02-14 15:32 UTC, abompard commented on REUSE.toml
> +SPDX-License-Identifier = "GPL-2.0-or-later"
You can use a wildcard in the path here as well: `configs/*`

2025-02-14 15:32 UTC, abompard commented on codecov.yml
> +
You don't need this since you flagged the file in `REUSE.toml`.

2025-02-14 15:32 UTC, abompard commented on packit/installation/main.fmf
> +
Now that you've added it to `REUSE.toml`, you can drop this change.

2025-02-14 15:32 UTC, abompard commented on tests/fixtures/bad_conf.toml
> +
The files in this directory have been added to `REUSE.toml`, no need for these changes anymore.

2025-02-18 08:25 UTC, abompard requested changes
You can remove the files in `configs/*.license` and `tests/fixtures/*.license` now, since the corresponding files are now covered in `REUSE.toml`.

2025-02-19 11:34 UTC, abompard requested changes

2025-02-19 11:34 UTC, abompard commented on .pre-commit-config.yaml
> +    rev: v0.8.2
This does not seem necessary, maybe a rebase fallout.

2025-02-19 11:34 UTC, abompard commented on news/383.docs.md
> +<!--
This comment is still current.

2025-02-19 11:34 UTC, abompard commented on tests/fixtures/msg_without_topic_dump.txt
> +
I don't think you need to add an empty line here.

2025-02-20 08:34 UTC, abompard requested changes
You can also remove the `news/*.license` files as they are covered by `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on .packit.yaml
> +# SPDX-FileCopyrightText: 2024 Red Hat, Inc
This file is already covered by the `.*.yaml` glob in `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on .pre-commit-config.yaml
> +# SPDX-FileCopyrightText: 2024 Red Hat, Inc
This file is already covered by the `.*.yaml` glob in `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on .readthedocs.yml
> +# SPDX-FileCopyrightText: 2024 Red Hat, Inc
This file is already covered by the `.*.yml` glob in `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on configs/fedora.stg.toml
> +# SPDX-FileCopyrightText: 2024 Red Hat, Inc
This file is already covered by the `configs/*` glob in `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on configs/fedora.toml
> +# SPDX-FileCopyrightText: 2024 Red Hat, Inc
This file is already covered by the `configs/*` glob in `REUSE.toml`.

2025-02-20 08:34 UTC, abompard commented on fm-consumer@.service
> +SPDX-License-Identifier: GPL-2.0-or-later
This requires a prefix comment. Systemd unit files are INI files, and therefore can use `;` or `#` as a comment prefix. I would go for `#` since that's what I see most of the files in `/usr/lib/systemd/system` using.

```suggestion
# SPDX-FileCopyrightText: 2024 Red Hat, Inc
# SPDX-License-Identifier: GPL-2.0-or-later
```

2025-02-20 12:46 UTC, abompard requested changes

2025-02-20 12:46 UTC, abompard commented on config.toml.example
> +SPDX-License-Identifier: GPL-2.0-or-later
This requires a comment as well.
```suggestion
# SPDX-FileCopyrightText: 2024 Red Hat, Inc
# SPDX-License-Identifier: GPL-2.0-or-later
```

2025-02-20 12:46 UTC, abompard commented on docs/requirements-readthedocs.txt
> +SPDX-License-Identifier: GPL-2.0-or-later
These lines must be commented out.

```suggestion
# SPDX-FileCopyrightText: 2024 Red Hat, Inc
# SPDX-License-Identifier: GPL-2.0-or-later
```

2025-02-20 12:46 UTC, abompard commented on docs/sample_schema_package/README
> +
This should be commented out but it's a plain text file. Maybe rename this file to `.md` and add the tags in a comment, as for `SECURITY.md`.

2025-02-21 14:10 UTC, abompard reviewed
Looks good, thanks!
Could you please squash your 3 commits into one? Then it'll be good to merge.

2025-02-28 14:56 UTC, abompard commented
There's still a merge conflict, could you please rebase with `git rebase origin/develop` please?

2025-02-28 22:13 UTC, olamidepeterojo commented
Done @abompard

2025-03-03 08:24 UTC, abompard approved these changes
Alright, looks good, thanks for your perseverance! :-)

2025-03-03 11:44 UTC, olamidepeterojo commented
haha...finally! Thanks @abompard

2025-03-07 14:51 UTC, merged